global:
  resolve_timeout: 5m
inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = critical
    target_matchers:
      - severity =~ warning|info
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = warning
    target_matchers:
      - severity = info
  - equal:
      - namespace
    source_matchers:
      - alertname = InfoInhibitor
    target_matchers:
      - severity = info
receivers:
  - name: Default
  - name: Watchdog
    webhook_configs:
      - url: >-
          https://hooks.slack.com/services/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
  - name: Critical
    webhook_configs:
      - url: >-
          https://hooks.slack.com/services/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
  - name: 'null'
route:
  group_by:
    - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: Default
  repeat_interval: 12h
  routes:
    - receiver: Watchdog
      match:
        alertname: Watchdog
    - matchers:
        - alertname = InfoInhibitor
      receiver: 'null'
    - receiver: Critical
      match:
        severity: critical
